version: "3.8"
volumes:
  pgData:
services:
  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pgData:/var/lib/postgresql/data
    ports:
      - 5434:5432 # 將容器的5432映射到主機的5434 因為目前運作中的week7的容器已經使用5432 運作中的week4的容器已經使用5433
    deploy:
      replicas: 1
    networks:
      - bootcamp_network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  bootcamp-fitness:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - bootcamp_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
        compress: "true"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${PORT}/healthcheck || exit 1
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 30s
    deploy:
      replicas: 1
networks:
  bootcamp_network:
